name-template: '$MAJOR.$MINOR.$PATCH-preview'
tag-template: '$MAJOR.$MINOR.$PATCH-preview'
change-template: '* $TITLE (#$NUMBER)'
branches:
  - master
categories:
- title: 'Templates'
  labels:
    - 'Changelog: Templates'
- title: 'Skills'
  labels:
    - 'Changelog: Skills'
- title: 'Libraries'
  labels:
    - 'Changelog: Libraries'
- title: 'Solutions'
  labels:
    - 'Changelog: Solutions'
- title: 'Virtual Assistant Chat Client (Android)'
  labels:
    - 'Changelog: Android'
- title: 'Botskills CLI'
  labels:
    - 'Changelog: CLI'

template: |
  ## What’s Changed

  $CHANGES
  
  ## Thanks to our contributors
  $CONTRIBUTORS
